---
databases:
  mysql:
    host:
    user:
    password:
    dbname:
    port:
jwt:
  secret:
  expired:
encrypt:
  additional:
  keystring:
smtp:
  sender_name:
  email:
  password:
  host:
  port:
server:
  address:
    frontend:
jaeger:
  Host: 192.168.2.100:6831
  ServiceName: boilerplate
  LogSpans: true
logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info